---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: accounts-service

outputs:
- name: build-output

params:
  TERM: dumb

run:
  path: accounts-service/ci/tasks/build-account-service/task.sh
