---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: patrickcrocker/lotc
    tag: 'latest'

inputs:
- name: accounts-service

outputs:
- name: itest

params:
  CF_API_URL:
  CF_SKIP_SSL:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:

run:
  path: accounts-service/ci/destroy/task.sh
